// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGA7zrz4qwT9BghGHxA6k0JJ51Owe4O5I',
    appId: '1:265529429819:web:ed13084ba5c26fe308f11e',
    messagingSenderId: '265529429819',
    projectId: 'allodoc-e8122',
    authDomain: 'allodoc-e8122.firebaseapp.com',
    storageBucket: 'allodoc-e8122.firebasestorage.app',
    measurementId: 'G-MQFZ7878XF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCR1_6vIgTFqSFoFGF-3zyc-APkJYGei7M',
    appId: '1:265529429819:android:7f47e098e004df0d08f11e',
    messagingSenderId: '265529429819',
    projectId: 'allodoc-e8122',
    storageBucket: 'allodoc-e8122.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCh444c7hntqIrJGYxV8IQGD51jRRtilYc',
    appId: '1:265529429819:ios:5593c516565f0c9e08f11e',
    messagingSenderId: '265529429819',
    projectId: 'allodoc-e8122',
    storageBucket: 'allodoc-e8122.firebasestorage.app',
    iosBundleId: 'com.example.alloDoc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCh444c7hntqIrJGYxV8IQGD51jRRtilYc',
    appId: '1:265529429819:ios:5593c516565f0c9e08f11e',
    messagingSenderId: '265529429819',
    projectId: 'allodoc-e8122',
    storageBucket: 'allodoc-e8122.firebasestorage.app',
    iosBundleId: 'com.example.alloDoc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGA7zrz4qwT9BghGHxA6k0JJ51Owe4O5I',
    appId: '1:265529429819:web:56cf29b58724f30408f11e',
    messagingSenderId: '265529429819',
    projectId: 'allodoc-e8122',
    authDomain: 'allodoc-e8122.firebaseapp.com',
    storageBucket: 'allodoc-e8122.firebasestorage.app',
    measurementId: 'G-N4EN84BQVF',
  );
}
